language: cpp
compiler:
    - gcc
    - clang

before_install:
# Install a newer CMake as Travis only supports v2.8.7.
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make && cd bin && ./Sample_test